import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../../styles/Home.module.css'

const ProductDetail: NextPage = () => {

  const router = useRouter();
  const { productId } = router.query;

  return (
    <div className={styles.container}>
      <Head>
        <title>Products: {productId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Products v2 : {productId}
        </h1>

        <p className={styles.description}>
          Dynamic Page with param{' '}
          <code className={styles.code}>[productId]</code>
        </p>

      </main>
    </div>
  )
}

export default ProductDetail
